### PR TITLE
Fix: Hyperlinks of 'For Vim' and 'For Emacs' interchanged

### PR DESCRIPTION
**Pull request by Pranav2612000**

### CODE REVIEW

**Comment by prertik** [comment]
Since you're at here, maybe explore this more and try to get those pages into HTML or another format so that it can be displayed into gitbook rather than a raw view of the `md` file. Can we explore further?
If otherwise, I can merge this.

**Comment by Pranav2612000** [comment]
Yeah! Sure! On it!

**Comment by Pranav2612000** [comment]
The files are in the format similar to the other files. I think there is some issue with the gitbook configuration,maybe these files haven't been linked, I am not sure. But these files are in the right format.

**Comment by prertik** [comment]
Okay, this seems like an issue with `gitbook`, will see it's configurations later. Thanks for your contribution.

**Review by prertik — APPROVED** [review]

**Pull request merged**
